{"integer_overflow_1": {"contract": "integer_overflow_1", "sourceLanguage": "Solidity", "count_risk_of_false_positives": 0, "list_vulnerabilities": ["ArithmeticVulnerability"], "rules": [{"id": "Arithmetic_4", "fullDescription": {"text": "A possible integer overflow exists in the function `add(uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer."}, "name": "ArithmeticVulnerability", "shortDescription": {"text": "Integer Overflow"}}, {"id": "Arithmetic_11", "name": "ArithmeticVulnerability", "shortDescription": {"text": "Integer Overflow."}}], "listLine": [14], "analysis": {"14": [{"level": "warning", "tool": ["mythril", "oyente"], "snippet": {"text": "sellerBalance += value"}, "fullDescription": "A possible integer overflow exists in the function `add(uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "name": "ArithmeticVulnerability"}]}, "count_vulnerabilities": {"ArithmeticVulnerability": 1}, "count_leve_vulnerabilities": {"warning": 1, "error": 0, "note": 0, "none": 0}, "false_positives": 0}, "mishandled": {"contract": "mishandled", "sourceLanguage": "Solidity", "count_risk_of_false_positives": 1, "list_vulnerabilities": ["AccessControlVulnerability", "UncheckedLowCallsVulnerability"], "rules": [{"id": "AccessControl_13", "fullDescription": {"text": "In the function `withdrawBalance()` a non-zero amount of Ether is sent to msg.sender.\nIt seems that this function can be called without restrictions."}, "name": "AccessControlVulnerability", "shortDescription": {"text": "Ether send"}}, {"id": "UncheckedLowCalls_3", "fullDescription": {"text": "The return value of an external call is not checked. Note that execution continue even if the called contract throws."}, "name": "UncheckedLowCallsVulnerability", "shortDescription": {"text": "Unchecked CALL return value"}}], "listLine": [14], "analysis": {"14": [{"level": "warning", "tool": ["mythril"], "snippet": {"text": "msg.sender.send(amountToWithdraw)"}, "fullDescription": "In the function `withdrawBalance()` a non-zero amount of Ether is sent to msg.sender.\nIt seems that this function can be called without restrictions.", "name": "AccessControlVulnerability"}, {"level": "note", "tool": ["mythril"], "fullDescription": "The return value of an external call is not checked. Note that execution continue even if the called contract throws.", "name": "UncheckedLowCallsVulnerability", "flag": "risk of false positives"}]}, "count_vulnerabilities": {"AccessControlVulnerability": 1, "UncheckedLowCallsVulnerability": 1}, "count_leve_vulnerabilities": {"warning": 1, "error": 0, "note": 1, "none": 0}, "false_positives": 0}, "send_loop": {"contract": "send_loop", "sourceLanguage": "Solidity", "count_risk_of_false_positives": 0, "list_vulnerabilities": [], "rules": [], "listLine": [], "analysis": {}, "count_vulnerabilities": {}, "count_leve_vulnerabilities": {"warning": 0, "error": 0, "note": 0, "none": 0}, "false_positives": 0}}